<?php
/**
 * Created by PhpStorm.
 * User: Hadi
 * Date: 2018/6/7
 * Time: 15:23
 */

namespace Hadilee\Okexclient;


use Illuminate\Support\Facades\Facade;

class OkexclientFacade extends Facade
{

    protected static function getFacadeAccessor()
    {
        //parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'okexclient';
    }

}